### ISSUE TITLE
Yamlにおける機能とAgentの提案

### ISSUE THREAD

**Issue by tkubo-i-eight** [snakajima/graphai#2]
GraphAI の Yaml で個人的に欲しいと思った機能や Agent をいくつか提案させていただきます。

GraphAI は基本的にはデータ構造をプログラムとして扱い、非同期処理を安全に行うという発想において、関数型言語(特に Lisp 系の言語)に類似していると思います。なのでそこで使われている概念や関数を Agent として持ち込めばより便利になるのかなと思いました。

ただ、Yaml だと複雑な処理は冗長な表現になりがちだと感じました(将来的に DSL の登場に期待)。

以下、ご検討いただければ幸いです。

## nodes の戻り値

`nodes`の戻り値は、どの`node`にも`isResult: true`が定義されていなければ、一番最後に評価した`node`の値を返していただきたいです。

## Agent の定義(defAgent)の提案

`yaml`の中で Agent が定義できたらいいなと思いました。普通に関数のように使えるというのもあるし、他の Agent の入力にコールバックとして使えないかなと思っています。

| 項目              | 内容                                 |
| :---------------- | :----------------------------------- |
| Agent 名          | defAgent                             |
| 処理内容          | Agent を定義します                   |
| 入力: inputs.args | Agent に入力する値を配列で定義します |
| 入力: inputs.body | Agent で行う処理。graph を定義します |
| 戻り値            | input.body を実行したときの戻り値    |

想定している使い方:

```yaml
version: 0.5
nodes:
  exampleAgent:
    # defAgentというAgentでAgentを定義します
    agent: defAgent
    inputs:
      # Agentがとる`inputs`を定義します
      args:
        - left
        - right
      # Agentが行う処理を記述します。graphを定義して実行します。
      body:
        nodes:
          output:
            agent: consoleAgent
            inputs:
              text: 'left: ${:left}, right: ${:right}'
  # 上記で定義した`exampleAgent`を実行します
  callExampleAgent:
    agent: exampleAgent
    inputs:
      left: 'this is left'
      right: 'this is right'
```

## caseAgent の提案

複数の条件で分岐できる Agent です。すでに`node.if`というのがありますが、既存のプログラミング言語の記述方法に近い形で書きたいという思いがありました。

| 項目                | 内容                                               |
| :------------------ | :------------------------------------------------- |
| Agent 名            | caseAgent                                          |
| 処理内容            | 複数の条件で分岐し処理を行います                   |
| 入力: inputs.conditions[].if   | 処理を行う条件                                     |
| 入力: inputs.conditions[].then | 条件とマッチした場合に行う処理。graph を記述します |
| 入力: inputs.conditions[].else | どの条件にもマッチしなかった時に行う処理です       |
| 戻り値              | マッチした条件の処理を実行したときの戻り値         |

想定している使い方:

```yaml
version: 0.5
nodes:
  hoge:
    value: 0
  # 条件分岐するnode
  comp:
    agent: caseAgent
    inputs:
      conditions:
        # 条件とマッチした場合に実行する処理を配列で定義します。
        - if:
            - :hoge
            - ==
            - 1
          # 条件にマッチした場合の処理。graphを定義して実行します。
          then:
            nodes:
              output:
                agent: consoleAgent
                inputs:
                  text: 'hoge is one'
        - if:
            - :hoge
            - <
            - 5
          then:
            nodes:
              output:
                agent: consoleAgent
                inputs:
                  text: 'hoge is less than 5'
        # 上記の全てにマッチしなかった場合
        - else:
            nodes:
              output:
                agent: consoleAgent
                inputs:
                  text: 'hoge is greater than or equal 5'
```

## loopAgent の提案

すでにループ機能はありますが、個人的にはループ(特に update のところ)が分かりづらかったので、既存のプログラミング言語に近い形で記述できた方が個人的には理解しやすいと思ったので提案させていただきます。

これは`Clojure`の[loop](https://clojuredocs.org/clojure.core/loop)を参考にしています。

| 項目                  | 内容                                         |
| :-------------------- | :------------------------------------------- |
| Agent 名              | loopAgent                                    |
| 処理内容              | ループして値を返します                       |
| 入力: inputs.init     | callback に最初に渡される値                    |
| 入力: inputs.callback | ループで行う処理                             |
| 戻り値                | 最後の input.callback を実行したときの戻り値 |

想定している使い方:

```yaml
version: 0.5
nodes:
  # loopAgentで使用するcallbackを定義します。上記で提案した`defAgent`を使用しています。
  callback:
    agent: defAgent
    inputs:
      # 前の回で更新された値が渡される
      args:
        - idx
        - cnt
      body:
        nodes:
          agent: caseAgent
          inputs:
            conditions:
              # ↓の疑似コードと一緒
              # if idx <= 10 then { next: true, return: { idx: idx + 1, cnt: cnt + 1 } }
              - if:
                  - :idx
                  - <=
                  - 10
                then:
                  nodes:
                    idx2:
                      agent: plusAgent
                      inputs:
                        values:
                          - :idx
                          - 1
                    count:
                      agent: plusAgent
                      inputs:
                        values:
                          - :cnt
                          - 1
                    result:
                      next: true
                      return:
                        idx: :idx2
                        cnt: :count
              # ↓の疑似コードと一緒
              # else { next: true, return: { idx, cnt } }
              - else:
                  nodes:
                    result:
                      next: false
                      return:
                        idx: :idx
                        cnt: :cnt
  countLoop:
    agent: loopAgent
    inputs:
      # 最初にcallbackのinputsに渡される値
      init:
        idx: 0
        cnt: 10
      # callbackを実行する
      callback: :callback
```
